### ISSUE TITLE
The App crashed after clicking "Add Icon" button.

### ISSUE THREAD

**Issue by ConstasJ** [LSPosed/WSAHelper#6] opened 2022-08-10 13:47 UTC
I install the MagiskOnWSA and use WSAHelper to restore the icons on the start menu.However,when I try to add icons,the application crashed every time without adding icons.

**Comment by MohammedMehdiTBER** [comment] 2022-08-26 20:58
Same issue here

**Comment by Howard20181** [comment] 2022-08-27 05:43
duplicate of #4

**Closed as completed by Howard20181** 2022-08-27 05:43 UTC
